name: Argo ci pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write 
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # or your specific region
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/frontend
      
      - name: Extract short commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: frontend/
          push: true
          tags: amolsontakke96/frontend:${{ steps.vars.outputs.sha_short }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: backend/
          push: true
          tags: amolsontakke96/backend:${{ steps.vars.outputs.sha_short }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Kubernetes manifest with new image tag
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ steps.vars.outputs.sha_short }}|" k8s/node/charts/frontend/values.yaml
      - name: Commit and push changes
        run: |
          git config user.name "${{ secrets.GIT_COMMITTER_NAME }}"
          git config user.email "${{ secrets.GIT_COMMITTER_EMAIL }}"
          git add k8s/node/charts/frontend/values.yaml
          git commit -m "Update image tag to ${{ steps.meta.outputs.version }}" || true
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
