name: Argo ci pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # or your specific region
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: frontend/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: backend/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Kubernetes manifest with new image tag
        run: |
          sed -i "s|^\([[:space:]]*tag:\).*|\1 \"${{ steps.meta.outputs.version }}\"|" k8s/node/charts/frontend/values.yaml
      - name: Commit and push changes
        run: |
          git config user.name "${{ secrets.GIT_COMMITTER_NAME }}"
          git config user.email "${{ secrets.GIT_COMMITTER_EMAIL }}"
          git add k8s/node/charts/frontend/values.yaml
          git commit -m "Update image tag to ${{ steps.meta.outputs.version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
